using System.Buffers.Binary;
using NSec.Cryptography;

namespace Expedition.Activation;

/// <summary>
/// Verifies EST- session tokens using the server's Ed25519 public key.
/// The public key can only verify signatures, not create them — extracting
/// it from the binary is useless for forging tokens.
/// </summary>
public static class SessionTokenVerifier
{
    private const byte TokenVersion = 0x01;
    private const int PayloadSize = 89;    // 1+16+32+8+8+2+1+21
    private const int SignatureSize = 64;   // Ed25519
    private const int TotalSize = PayloadSize + SignatureSize; // 153 bytes
    private const string TokenPrefix = "EST-";

    private static readonly SignatureAlgorithm Algorithm = SignatureAlgorithm.Ed25519;

    // Server's Ed25519 public key (32 bytes).
    // Generated by generate_ed25519_keys.py
    private static readonly byte[] ServerPublicKeyBytes = new byte[]
    {
        0x39, 0x95, 0xFF, 0x12, 0xD8, 0xBB, 0x9A, 0xDE,
        0xC8, 0x11, 0x87, 0x9A, 0xA4, 0xC1, 0x4D, 0xF6,
        0x67, 0x1F, 0x39, 0x6B, 0x4F, 0xEB, 0x21, 0xFB,
        0x85, 0x4B, 0x02, 0x75, 0xAE, 0xFC, 0x25, 0x75,
    };

    private static readonly PublicKey ServerPublicKey =
        PublicKey.Import(Algorithm, ServerPublicKeyBytes, KeyBlobFormat.RawPublicKey);

    /// <summary>
    /// Verifies and parses an EST- session token.
    /// Returns null if the token is invalid, has a bad signature, or is malformed.
    /// </summary>
    public static SessionToken? Verify(string tokenString)
    {
        if (string.IsNullOrWhiteSpace(tokenString))
            return null;

        if (!tokenString.StartsWith(TokenPrefix, StringComparison.OrdinalIgnoreCase))
            return null;

        var encoded = tokenString[TokenPrefix.Length..];

        // Base64url decode (add padding as needed)
        var padding = (4 - encoded.Length % 4) % 4;
        var padded = encoded + new string('=', padding);
        padded = padded.Replace('-', '+').Replace('_', '/');

        byte[] raw;
        try
        {
            raw = Convert.FromBase64String(padded);
        }
        catch
        {
            return null;
        }

        if (raw.Length != TotalSize)
            return null;

        var payload = raw.AsSpan(0, PayloadSize);
        var signature = raw.AsSpan(PayloadSize, SignatureSize);

        // Verify Ed25519 signature
        if (!Algorithm.Verify(ServerPublicKey, payload, signature))
            return null;

        // Parse payload
        var version = payload[0];
        if (version != TokenVersion)
            return null;

        var keyId = new Guid(payload.Slice(1, 16));
        var machineIdHash = payload.Slice(17, 32).ToArray();
        var issuedAt = BinaryPrimitives.ReadInt64BigEndian(payload.Slice(49, 8));
        var expiresAt = BinaryPrimitives.ReadInt64BigEndian(payload.Slice(57, 8));
        var pluginVersion = BinaryPrimitives.ReadUInt16BigEndian(payload.Slice(65, 2));
        var flags = payload[67];

        return new SessionToken
        {
            KeyId = keyId,
            MachineIdHash = machineIdHash,
            IssuedAt = DateTimeOffset.FromUnixTimeSeconds(issuedAt).UtcDateTime,
            ExpiresAt = DateTimeOffset.FromUnixTimeSeconds(expiresAt).UtcDateTime,
            PluginVersion = pluginVersion,
            Flags = flags,
        };
    }
}
